#!/usr/bin/env python3
import subprocess
import sys
import select

timeout = 1

while True:
    process = subprocess.Popen(sys.argv[1:])
    result = process.wait()
    if result:
        print('Retrying after {}s'.format(timeout))
        if select.select([sys.stdin, ], [], [], timeout)[0]:
            timeout = 1
            sys.stdin.read(1)
        else:
            timeout = 2 * timeout

